# Generated by Django 4.2.5 on 2023-09-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=50, verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=255, verbose_name='почта')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный')], default='active', max_length=50, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
                'ordering': ('date_added',),
            },
        ),
        migrations.CreateModel(
            name='ContactsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'список контакта',
                'verbose_name_plural': 'списки контактов',
                'ordering': ('list',),
            },
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название списка')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contacts', models.ManyToManyField(through='contacts.ContactsList', to='contacts.contacts')),
            ],
            options={
                'verbose_name': 'список',
                'verbose_name_plural': 'списки',
                'ordering': ('date_added',),
            },
        ),
    ]
