# Generated by Django 4.2.5 on 2023-09-14 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='название рассылки')),
                ('message_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='тема сообщения')),
                ('message_content', models.TextField(blank=True, null=True, verbose_name='сообщение')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('contact_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.lists', verbose_name='Списки контактов')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_periods', models.CharField(blank=True, choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], max_length=50, null=True, verbose_name='периодичность рассылки')),
                ('status', models.CharField(blank=True, choices=[('new', 'новая'), ('running', 'запущена'), ('completed', 'завершена')], max_length=50, null=True, verbose_name='статус рассылки')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='дата начала')),
                ('mailing_time', models.TimeField(blank=True, null=True, verbose_name='время рассылки')),
                ('mailing_week_day_num', models.IntegerField(blank=True, null=True, verbose_name='день недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='дата окончания')),
                ('cron_setting', models.TextField(blank=True, null=True, verbose_name='настройка CRON')),
                ('mailing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'Настройки рассылки',
                'verbose_name_plural': 'настройки рассылок',
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='setting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_settings', to='mailing.mailingsettings', verbose_name='настройки рассылки'),
        ),
    ]
