# Generated by Django 4.2.5 on 2023-09-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt', models.DateTimeField(auto_now_add=True, verbose_name='последня попытка')),
                ('attempt_status', models.CharField(blank=True, choices=[('ok', 'Удачная попытка'), ('error', 'Неудачная попытка')], max_length=50, null=True, verbose_name='статус попытки')),
            ],
            options={
                'verbose_name': 'Настройки рассылки',
                'verbose_name_plural': 'настройки рассылок',
            },
        ),
    ]
